name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip' # caching pip dependencies
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install apache-airflow==2.7.2
        pip install -r requirements.txt
    -
      name: Analyzing the code with Pylint
      run: |
        pylint $(git ls-files '*.py')
